"""empty message

Revision ID: 575732399c16
Revises: b91e41f8a879
Create Date: 2021-02-28 17:37:26.999901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575732399c16'
down_revision = 'b91e41f8a879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('book_id', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'book_id')
    # ### end Alembic commands ###
