"""empty message

Revision ID: 61dd001a6505
Revises: 8ffc4553d0c0
Create Date: 2021-02-28 21:07:54.000900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dd001a6505'
down_revision = '8ffc4553d0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_id', sa.String(length=36), nullable=False))
    op.drop_column('images', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_column('images', 'file_id')
    # ### end Alembic commands ###
